scss_files: "sass/**/*.scss"

exclude: 'css/**/*.css'

lintes:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: true

  # ColorKeyword:
  #   enabled: true

  BorderZero:
    enabled: false

  Indentation:
    # exclude:
    #   - 'path/to/file.scss'
    #   - 'path/to/directory/**'
    severity: warning
    width: 2
